#!/bin/bash
source lib/timing-functions
source lib/disk-cache

#flush-cache
begin sequential read
end $(cat data/sequential | wc -c)

random_list="$(ls data/chunk-* | shuf)"
#flush-cache
begin random reads without process overhead
end $(cat $random_list | wc -c)

#flush-cache
begin quasi-sequential reads without process overhead
end $(cat data/chunk-* | wc -c)
