#!/bin/bash
source lib/timing-functions

rm -rf data
mkdir data

begin initializing chunks
for (( i = 0; i < 10000; ++i )); do
  dd if=/dev/zero of=data/chunk-$i bs=1M count=1 >& /dev/null
done
end

run() {
  local n=$1
  local seed=${2:-5811}
  local size=$((100000 / $n))

  begin generating $n chunks with $seed, each ${size}k
  for (( i = 0; i < $n; ++i )); do
    dd if=/dev/zero of=data/chunk-$((i * seed % 10000)) bs=1K count=$size >& /dev/null
  done
  end

  begin generating $n chunks with $seed, each ${size}k, in parallel
  for (( i = 0; i < $n; ++i )); do
    dd if=/dev/zero of=data/chunk-$((i * (seed + 17) % 10000)) bs=1K count=$size >& /dev/null &
  done
  end
}

run 10000 2819
run 1000  2819
run 100   2819
run 10    2819
run 1     2819

run 10000 5131
run 1000  5131
run 100   5131
run 10    5131
run 1     5131
