#!/bin/bash

begin() {
  timestamp=$(date +%s%N)
  echo -n "$*: "
}

end() {
  bytes=$1
  wait
  sync
  local endtime=$(date +%s%N)
  local milliseconds=$(((endtime - timestamp) / 1000000))
  local bytes_per_millisecond=$((bytes / milliseconds))
  echo ${milliseconds}ms = ${bytes_per_millisecond}k/sec
}
